# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Message-Attachment-Stripper
version:      1.01
version_from: lib/Mail/Message/Attachment/Stripper.pm
installdirs:  site
requires:
    Mail::Message:                 2.05
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
